baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = 'Domum Social'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  themeVariant = ['domum-light', 'domum-dark']
  # SEO Configuration
  keywords = ['domum social', 'mastodon', 'tor', 'onion', 'anonymous social media', 'privacy', 'documentation', 'fediverse']
  author.name = 'Domum Social'
  
  # Open Graph defaults
  [params.og]
    image = '/favicon.ico'
    type = 'website'
  
  # Twitter Card defaults
  [params.twitter]
    card = 'summary'

[[menu.shortcuts]]
name = "Social Site"
url = "../"
weight = -10
pre = "<i class=\"fa-fw fab fa-mastodon\"></i>"

# required due to "card" shortcode rendering bug
# https://github.com/McShelby/hugo-theme-relearn/issues/1160
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
