baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = 'Domum Social'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  themeVariant = ['domum-light', 'domum-dark']

[[menu.shortcuts]]
name = "Social Site"
url = "../"
weight = -10
pre = "<i class=\"fa-fw fab fa-mastodon\"></i>"
