baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = 'Domum Social'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  themeVariant = ['domum-dark', 'domum-light']